# Generated by Django 5.2.1 on 2025-05-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='updated_at',
        ),
    ]
